# Generated by Django 3.0.6 on 2020-07-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20200710_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='thumbnail',
            field=models.ImageField(default='blank.svg', upload_to='thumbnails'),
        ),
    ]
