# Generated by Django 2.2.14 on 2020-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_bookmark_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='thumbnail',
            field=models.ImageField(default='blank.svg', upload_to='bookmarks/thumbnails'),
        ),
    ]
