# Generated by Django 3.0.6 on 2020-06-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageLink', models.CharField(max_length=512)),
                ('pageTitle', models.CharField(max_length=128)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.Folder')),
            ],
        ),
    ]
